# Generated by Django 3.2.9 on 2021-12-02 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('reg_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('chassis_no', models.CharField(max_length=10)),
                ('load_capacity', models.IntegerField()),
                ('tyre_size', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_commissioned', models.DateTimeField()),
                ('date_decommissioned', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('Sold', 'Sold'), ('Retired', 'Retired'), ('Written Off', 'Written Off'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Duty', 'On Duty'), ('Under Maintenance', 'Under Maintenance')], max_length=50)),
                ('model', models.CharField(max_length=20)),
                ('engine_no', models.CharField(max_length=10)),
                ('diff_count', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=10)),
                ('fuel_tank_capacity', models.IntegerField()),
                ('odometer_reading', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('reg_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('chassis_no', models.CharField(max_length=10)),
                ('load_capacity', models.IntegerField()),
                ('tyre_size', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_commissioned', models.DateTimeField()),
                ('date_decommissioned', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('Sold', 'Sold'), ('Retired', 'Retired'), ('Written Off', 'Written Off'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Duty', 'On Duty'), ('Under Maintenance', 'Under Maintenance')], max_length=50)),
                ('type', models.CharField(choices=[('FB', 'Flat Bed'), ('SK', 'Skeletal'), ('CB', 'Closed Body'), ('HS', 'High Sided'), ('TP', 'Tipper'), ('TK', 'Tanker'), ('LL', 'Low Loader'), ('CC', 'Coil Carrier')], max_length=20)),
                ('axle_count', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six')], default=3)),
                ('mounted_truck', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.truck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('id_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('phone_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('dob', models.DateField()),
                ('date_hired', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('nok_first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('nok_last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('nok_phone_no', models.CharField(max_length=10, verbose_name='Phone No.')),
                ('nok_relationship', models.CharField(max_length=30, verbose_name='Relationship')),
                ('nok_id_no', models.CharField(max_length=10, verbose_name='ID. No.')),
                ('nok_email', models.EmailField(max_length=50, verbose_name='Email')),
                ('assigned_truck', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.truck')),
            ],
        ),
    ]
