# Generated by Django 3.2.9 on 2021-12-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_auto_20211202_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('On Duty', 'On Duty'), ('Under Maintenance', 'Under Maintenance')], default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='truck',
            name='diff_count',
            field=models.IntegerField(choices=[('1', 'ONE'), ('2', 'TWO'), ('3', 'THREE')], default='2'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('On Duty', 'On Duty'), ('Under Maintenance', 'Under Maintenance')], default='Available', max_length=50),
        ),
    ]
