# Generated by Django 3.2.9 on 2021-12-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_auto_20211202_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='diff_count',
            field=models.IntegerField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three')], default='2'),
        ),
    ]
