# Generated by Django 3.2.9 on 2021-12-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_alter_truck_diff_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='axle_count',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='3', max_length=1),
        ),
    ]
