# Generated by Django 3.2.9 on 2021-12-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_alter_trailer_axle_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='type',
            field=models.CharField(choices=[('FB', 'Flat Bed'), ('SK', 'Skeletal'), ('CB', 'Closed Body'), ('HS', 'High Sided'), ('TP', 'Tipper'), ('TK', 'Tanker/Monoblock'), ('LL', 'Low Loader'), ('CC', 'Coil Carrier')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='driver',
            unique_together={('first_name', 'last_name', 'id_no', 'assigned_truck')},
        ),
        migrations.AlterUniqueTogether(
            name='trailer',
            unique_together={('reg_no', 'mounted_truck')},
        ),
    ]
